<?php

namespace Database\Seeders;

use App\Models\L2GI;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class L2GISeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $etudiants = [
            ['matricule' => '24INF00649S', 'nom' => 'ABBE MOREL RAYAN', 'telephone' => null, 'email' => 'morel.abbe@iua.ci'],
            ['matricule' => '24INF00542S', 'nom' => 'ADENIYI SAMY CORNEILLE', 'telephone' => null, 'email' => 'samy.adeniyi@iua.ci'],
            ['matricule' => '24INF00289B', 'nom' => 'ADJIDAN KONAN CHRIS ALAN', 'telephone' => null, 'email' => 'chris.adjidan@iua.ci'],
            ['matricule' => '24INF01019S', 'nom' => 'ADJIE AKOUHA MARIE JOELLE', 'telephone' => null, 'email' => 'marie.adjie@iua.ci'],
            ['matricule' => '24INF01701S', 'nom' => 'ADOU  YVES-MARIE', 'telephone' => null, 'email' => 'yves.adou@iua.ci'],
            ['matricule' => '24INF02042S', 'nom' => 'AKA ECHE PAUL-EMMANUEL YANIS', 'telephone' => null, 'email' => 'emmanuel.aka@iua.ci'],
            ['matricule' => '24INF01044S', 'nom' => 'ALLOGNON HOUETCHEHOUN TSAKIEL', 'telephone' => null, 'email' => 'houetchehoun.allognon@iua.ci'],
            ['matricule' => '24INF00628S', 'nom' => 'AMANKOU SAMUEL AYMERIC', 'telephone' => null, 'email' => 'samuel.amankou@iua.ci'],
            ['matricule' => '24INF00235S', 'nom' => 'AMOUSSOU ETIENNE-ELIE', 'telephone' => null, 'email' => 'etienne.amoussou@iua.ci'],
            ['matricule' => '24INF01120S', 'nom' => 'ASSE  ROANE DAVID STYNE HALADJ', 'telephone' => null, 'email' => 'styne.asse@iua.ci'],
            ['matricule' => '24INF00712', 'nom' => 'ASSI APIE MARIE EMMANUELLA', 'telephone' => null, 'email' => 'marie.assi@iua.ci'],
            ['matricule' => '24INF00269S', 'nom' => 'ASSIENAN KOFFI PRINCE DIDIME', 'telephone' => null, 'email' => 'prince.assienan@iua.ci'],
            ['matricule' => '24INF00401S', 'nom' => 'ASSOUAN  MARC-ELIE KOUASSI DAN', 'telephone' => null, 'email' => 'kouassi.assouan@iua.ci'],
            ['matricule' => '24INF00687S', 'nom' => 'ATSE  YEBI ENOCK EMMANUEL', 'telephone' => null, 'email' => 'enock.atse@iua.ci'],
            ['matricule' => '24INF00183S', 'nom' => 'ATTOKPA KOUASSI CHRIS-O\'NEAL H', 'telephone' => null, 'email' => 'o\'neal.attokpa@iua.ci'],
            ['matricule' => '24INF01416S', 'nom' => 'AVENIE KISSI SAMUEL MARDOCHEE', 'telephone' => null, 'email' => 'samuel.avenie@iua.ci'],
            ['matricule' => '24INF00215S', 'nom' => 'BABO  DANIEL PHINEE', 'telephone' => null, 'email' => 'daniel.babo@iua.ci'],
            ['matricule' => '24INF00112S', 'nom' => 'BADOLO ISRAEL SAMUEL ELISEE', 'telephone' => null, 'email' => 'samuel.badolo@iua.ci'],
            ['matricule' => '24INF00224B', 'nom' => 'BAH MAMADOU ALIOU', 'telephone' => null, 'email' => 'mamadou.bah@iua.ci'],
            ['matricule' => '24INF01693S', 'nom' => 'BAKAYOKO ABOUBAKAR', 'telephone' => null, 'email' => 'bakayoko.bakayoko@iua.ci'],
            ['matricule' => '24INF00329B', 'nom' => 'BALE BASHIRAT ADUKE OPEYEMI', 'telephone' => null, 'email' => 'aduke.bale@iua.ci'],
            ['matricule' => '24INF04088S', 'nom' => 'BALKISOU MANOMBA LABARAN', 'telephone' => null, 'email' => 'manomba.balkisou@iua.ci'],
            ['matricule' => '24INF01489S', 'nom' => 'BAO DORGELES OLIVE SANDRA', 'telephone' => null, 'email' => 'olive.bao@iua.ci'],
            ['matricule' => '24INF01447S', 'nom' => 'BEH  DEGRY JEREMIE HARDING', 'telephone' => null, 'email' => 'jeremie.beh@iua.ci'],
            ['matricule' => '23INF02326', 'nom' => 'BEKE  WOGNIN NOE RUBEN EMMANUE', 'telephone' => null, 'email' => 'ruben.beke@iua.ci'],
            ['matricule' => '24INF00052B', 'nom' => 'BERTE MORIFERE ABDELATIF', 'telephone' => null, 'email' => 'morifere.berte@iua.ci'],
            ['matricule' => '24INF00622S', 'nom' => 'BEUGRE JEAN-HUGUES ARMAND', 'telephone' => null, 'email' => 'hugues.beugre@iua.ci'],
            ['matricule' => '24INF00333S', 'nom' => 'BILSON EMMANUEL MIYOUMSA ELISH', 'telephone' => null, 'email' => 'miyoumsa.bilson@iua.ci'],
            ['matricule' => '24INF00609S', 'nom' => 'BISSA   EMMANUEL CHRYS AUREL', 'telephone' => null, 'email' => 'chrys.bissa@iua.ci'],
            ['matricule' => '24INF01569S', 'nom' => 'BOLI BI IRIE ANGE-VIANNEY', 'telephone' => null, 'email' => 'ange.boli@iua.ci'],
            ['matricule' => '24INF00356B', 'nom' => 'BOSSON AISSAN JEAN-JAURIS YVAN', 'telephone' => null, 'email' => 'jauris.bosson@iua.ci'],
            ['matricule' => '24INF00612S', 'nom' => 'BROU  CHRIS GEOFFROY DIMITRI', 'telephone' => null, 'email' => 'geoffroy.brou@iua.ci'],
            ['matricule' => '24INF00524S', 'nom' => 'BROU DIBY ULRICH', 'telephone' => null, 'email' => 'diby.brou@iua.ci'],
            ['matricule' => '24INF01090S', 'nom' => 'CAMARA  DJENEBA', 'telephone' => null, 'email' => 'camara.camara@iua.ci'],
            ['matricule' => '24INF02061S', 'nom' => 'CHATIGRE  KONANKAN ADRIEL', 'telephone' => null, 'email' => 'konankan.chatigre@iua.ci'],
            ['matricule' => '24INF00206S', 'nom' => 'CHOUMAN RAFIC KODOR', 'telephone' => null, 'email' => 'rafic.chouman@iua.ci'],
            ['matricule' => '24INF01229S', 'nom' => 'COULIBALY THIEGNON MOUHAMED', 'telephone' => null, 'email' => 'thiegnon.coulibaly@iua.ci'],
            ['matricule' => '24INF01670', 'nom' => 'COULIBALY YENASSONGUIYETA OUMA', 'telephone' => null, 'email' => 'yenassonguiyeta.coulibaly@iua.ci'],
            ['matricule' => '24INF00979S', 'nom' => 'COULIBALY YOH LOUISE SALIMATA', 'telephone' => null, 'email' => 'louise.coulibaly@iua.ci'],
            ['matricule' => '24INF01047S', 'nom' => 'COULIBALY ZIE ABDEL-AZIZ', 'telephone' => null, 'email' => 'abdel.coulibaly@iua.ci'],
            ['matricule' => '24INF00128S', 'nom' => 'DIABAGATE  ABDUL LATIF', 'telephone' => null, 'email' => 'abdul.diabagate@iua.ci'],
            ['matricule' => '24INF01135S', 'nom' => 'DIABATE  OUMAR', 'telephone' => null, 'email' => 'diabate.diabate@iua.ci'],
            ['matricule' => '24INF00152B', 'nom' => 'DIARASSOUBA ABDOUL RAHAMANE RA', 'telephone' => null, 'email' => 'rahamane.diarassouba@iua.ci'],
            ['matricule' => '24INF00013B', 'nom' => 'DIARRASSOUBA  ABDOUL LATIF', 'telephone' => null, 'email' => 'abdoul.diarrassouba@iua.ci'],
            ['matricule' => '24INF00685S', 'nom' => 'DIARRASSOUBA MOUSTAPHA ABDALA', 'telephone' => null, 'email' => 'moustapha.diarrassouba@iua.ci'],
            ['matricule' => '24INF00292B', 'nom' => 'DIBY FRANCK HAULLAND EMMANUEL', 'telephone' => null, 'email' => 'haulland.diby@iua.ci'],
            ['matricule' => '24INF00134B', 'nom' => 'DIOMANDE SEGBE ISMAEL', 'telephone' => null, 'email' => 'segbe.diomande@iua.ci'],
            ['matricule' => '24INF0908S', 'nom' => 'DIPRO LAVRY KETSIA EVE-NISSI', 'telephone' => null, 'email' => 'eve.dipro@iua.ci'],
            ['matricule' => '24INF01370S', 'nom' => 'DJA  PRINCE AUREOL', 'telephone' => null, 'email' => 'prince.dja@iua.ci'],
            ['matricule' => '24INF00222S', 'nom' => 'DJOBO DAGO ADRIEL JERIEL', 'telephone' => null, 'email' => 'adriel.djobo@iua.ci'],
            ['matricule' => '24INF00812S', 'nom' => 'DOSSO ADJA NOGODALE', 'telephone' => null, 'email' => 'adja.dosso@iua.ci'],
            ['matricule' => '24INF00498S', 'nom' => 'DOUMBIA  MOHAMED', 'telephone' => null, 'email' => 'doumbia.doumbia@iua.ci'],
            ['matricule' => '24INF01099S', 'nom' => 'DOUMBIA HASSAN ABRAHAM JEAN EM', 'telephone' => null, 'email' => 'jean.doumbia@iua.ci'],
            ['matricule' => '24INF01868S', 'nom' => 'DOUMBIA IBRAHIM AZIZ', 'telephone' => null, 'email' => 'ibrahim.doumbia@iua.ci'],
            ['matricule' => '24INF00173S', 'nom' => 'DOZOUNON MARIE ANGE CHRISTELLE', 'telephone' => null, 'email' => 'ange.dozounon@iua.ci'],
            ['matricule' => '24INF01687S', 'nom' => 'EKOH AFFOUE FABIOLA', 'telephone' => null, 'email' => 'affoue.ekoh@iua.ci'],
            ['matricule' => '24INF00587S', 'nom' => 'EKRA KOBENAN JEAN-CHRIS AURELE', 'telephone' => null, 'email' => 'chris.ekra@iua.ci'],
            ['matricule' => '24AA00206B', 'nom' => 'ELLOH KOUADIO JOHAN', 'telephone' => null, 'email' => 'kouadio.elloh@iua.ci'],
            ['matricule' => '24INF00612B', 'nom' => 'EROUBINOU  TOUMBI ADETONA JEAN', 'telephone' => null, 'email' => 'adetona.eroubinou@iua.ci'],
            ['matricule' => '24INF01035S', 'nom' => 'ESSOIN ASSIE CELESTIN', 'telephone' => null, 'email' => 'assie.essoin@iua.ci'],
            ['matricule' => '24INF00060S', 'nom' => 'FOFANA FALIKOU', 'telephone' => null, 'email' => 'fofana.fofana@iua.ci'],
            ['matricule' => '24INF00241S', 'nom' => 'FOFANA SANGA ABDOUL KARIM', 'telephone' => null, 'email' => 'abdoul.fofana@iua.ci'],
            ['matricule' => '24INF00139B', 'nom' => 'GBELIA HANLEY ANDRES JORIS', 'telephone' => null, 'email' => 'andres.gbelia@iua.ci'],
            ['matricule' => '24INF00246S', 'nom' => 'GNOHOU FRANCK', 'telephone' => null, 'email' => 'gnohou.gnohou@iua.ci'],
            ['matricule' => '24INF01123S', 'nom' => 'GONDO TOMAIN JEAN-CHRIST ROCHE', 'telephone' => null, 'email' => 'christ.gondo@iua.ci'],
            ['matricule' => '24INF00093B', 'nom' => 'GOORE BI AZA NATHANAEL', 'telephone' => null, 'email' => 'aza.goore@iua.ci'],
            ['matricule' => '24INF01355S', 'nom' => 'GOUENE  TENEGNAN LOÏC', 'telephone' => null, 'email' => 'tenegnan.gouene@iua.ci'],
            ['matricule' => '24INF00121B', 'nom' => 'GUEA  GEORGES-PATRICK NANOUX E', 'telephone' => null, 'email' => 'nanoux.guea@iua.ci'],
            ['matricule' => '24INF00673S', 'nom' => 'GUEYE GNONSIECAN LOIC-EMMANUEL', 'telephone' => null, 'email' => 'loic.gueye@iua.ci'],
            ['matricule' => '24INF00984S', 'nom' => 'HIE OKOU CHARLES YORISSE EMMAN', 'telephone' => null, 'email' => 'yorisse.hie@iua.ci'],
            ['matricule' => '24INF00146S', 'nom' => 'HIEN SIE HENRI JOEL', 'telephone' => null, 'email' => 'henri.hien@iua.ci'],
            ['matricule' => '24INF01727S', 'nom' => 'HODONOU SOUROU DORGELIN EZECHI', 'telephone' => null, 'email' => 'dorgelin.hodonou@iua.ci'],
            ['matricule' => '24INF01340S', 'nom' => 'HOTO GUY ANS IVAN', 'telephone' => null, 'email' => 'ans.hoto@iua.ci'],
            ['matricule' => '24INF01305S', 'nom' => 'KABORE  MOHAMED', 'telephone' => null, 'email' => 'kabore.kabore@iua.ci'],
            ['matricule' => '24INF00971S', 'nom' => 'KABORE  YOUGONE ABDOUL HENRI J', 'telephone' => null, 'email' => 'henri.kabore@iua.ci'],
            ['matricule' => '24INF00479S', 'nom' => 'KABRAN KOFFI RICHMOND ANGE AUR', 'telephone' => null, 'email' => 'ange.kabran@iua.ci'],
            ['matricule' => '24INF01571S', 'nom' => 'KANDE KARAMOKO', 'telephone' => null, 'email' => 'kande.kande@iua.ci'],
            ['matricule' => '24INF00516S', 'nom' => 'KANGA MARC ROXAN', 'telephone' => null, 'email' => 'marc.kanga@iua.ci'],
            ['matricule' => '24INF01385S', 'nom' => 'KANGOUTE ISMAËL', 'telephone' => null, 'email' => 'kangoute.kangoute@iua.ci'],
            ['matricule' => '24INF00845S', 'nom' => 'KATIO  MEMASSA ALAIN WILFRIED', 'telephone' => null, 'email' => 'alain.katio@iua.ci'],
            ['matricule' => '24INF01386S', 'nom' => 'KOBLAN JOSUE CHRIST YVAN', 'telephone' => null, 'email' => 'christ.koblan@iua.ci'],
            ['matricule' => '24SIC00127S', 'nom' => 'KODJO  SALOMON JOEL', 'telephone' => null, 'email' => 'salomon.kodjo@iua.ci'],
            ['matricule' => '24INF01368S', 'nom' => 'KOFFI  ARIEL JONATHAN', 'telephone' => null, 'email' => 'ariel.koffi@iua.ci'],
            ['matricule' => '24INF00243S', 'nom' => 'KOFFI  CHRIST OTHNIEL BENI', 'telephone' => null, 'email' => 'othniel.koffi@iua.ci'],
            ['matricule' => '24INF00409B', 'nom' => 'KOKOUA NANCET ERICKA YASMINE', 'telephone' => null, 'email' => 'ericka.kokoua@iua.ci'],
            ['matricule' => '23INF01520', 'nom' => 'KONE  ABDOUL AZIZ', 'telephone' => null, 'email' => 'abdoul.kone@iua.ci'],
            ['matricule' => '24INF01862S', 'nom' => 'KONE EKARNE HABIB EMMANUEL', 'telephone' => null, 'email' => 'habib.kone@iua.ci'],
            ['matricule' => '24INF00618S', 'nom' => 'KONE MALIKA KATIENAI ANNIE', 'telephone' => null, 'email' => 'katienai.kone@iua.ci'],
            ['matricule' => '24INF00190B', 'nom' => 'KONE MEA JEAN VIANNEY', 'telephone' => null, 'email' => 'jean.kone@iua.ci'],
            ['matricule' => '24INF00416S', 'nom' => 'KONE MOUSSA', 'telephone' => null, 'email' => 'kone.kone@iua.ci'],
            ['matricule' => '24INF00476S', 'nom' => 'KONE MOUSTAPHA', 'telephone' => null, 'email' => 'kone.kone@iua.ci'],
            ['matricule' => '24INF00909S', 'nom' => 'KONI BETSALEEL ANGE DANIEL', 'telephone' => null, 'email' => 'ange.koni@iua.ci'],
            ['matricule' => '24INF02044S', 'nom' => 'KORE ADORATION', 'telephone' => null, 'email' => 'kore.kore@iua.ci'],
            ['matricule' => '24INF01730S', 'nom' => 'KOSSONOU  EMMA ABENAN CHRISTEL', 'telephone' => null, 'email' => 'abenan.kossonou@iua.ci'],
            ['matricule' => '24INF00801S', 'nom' => 'KOUADIO JEAN EPHREM VIANNEY', 'telephone' => null, 'email' => 'ephrem.kouadio@iua.ci'],
            ['matricule' => '24INF00288S', 'nom' => 'KOUADIO KEVIN MARC-ARMEL', 'telephone' => null, 'email' => 'marc.kouadio@iua.ci'],
            ['matricule' => '24INF01452S', 'nom' => 'KOUADIO NOELLIE MALIKA MARCELL', 'telephone' => null, 'email' => 'malika.kouadio@iua.ci'],
            ['matricule' => '24INF00886S', 'nom' => 'KOUAKOU  KHAN ANDRE JOSEPH', 'telephone' => null, 'email' => 'andre.kouakou@iua.ci'],
            ['matricule' => '24INF00539S', 'nom' => 'KOUAKOU  KOUADIO JEAN-NOEL', 'telephone' => null, 'email' => 'jean.kouakou@iua.ci'],
            ['matricule' => '24INF05555S', 'nom' => 'KOUAKOU  KOUASSI JÖEL CEDRIC', 'telephone' => null, 'email' => 'jöel.kouakou@iua.ci'],
            ['matricule' => '24INF02029S', 'nom' => 'KOUAKOU  MARIE ORNELLA ROXANE', 'telephone' => null, 'email' => 'ornella.kouakou@iua.ci'],
            ['matricule' => '24INF01297S', 'nom' => 'KOUAME  KOUAKOU PAUL-MARIE EMM', 'telephone' => null, 'email' => 'marie.kouame@iua.ci'],
            ['matricule' => '24INF00663S', 'nom' => 'KOUAME  OTTISSEFA CHRIST-MARVE', 'telephone' => null, 'email' => 'christ.kouame@iua.ci'],
            ['matricule' => '23AA01593', 'nom' => 'KOUAME NIAMIEN ANGE EMMANUEL', 'telephone' => null, 'email' => 'ange.kouame@iua.ci'],
            ['matricule' => '24INF00666S', 'nom' => 'KOUAO  BLAISE JUNIOR ELISE', 'telephone' => null, 'email' => 'junior.kouao@iua.ci'],
            ['matricule' => '24INF00665S', 'nom' => 'KOUAO BLAISE JUNIOR EPHRAIM', 'telephone' => null, 'email' => 'junior.kouao@iua.ci'],
            ['matricule' => '24INF00312S', 'nom' => 'KOUASSI ADAMO CHRIST MATHIEU D', 'telephone' => null, 'email' => 'mathieu.kouassi@iua.ci'],
            ['matricule' => '24INF01680S', 'nom' => 'KOUTON  LANDRY MAWULOME HABIB', 'telephone' => null, 'email' => 'mawulome.kouton@iua.ci'],
            ['matricule' => '24INF01595S', 'nom' => 'KUYA  SON ARMEL', 'telephone' => null, 'email' => 'son.kuya@iua.ci'],
            ['matricule' => '24INF00515S', 'nom' => 'MAGES ORLANE MARIE-NOEMIE JEAN', 'telephone' => null, 'email' => 'noemie.mages@iua.ci'],
            ['matricule' => '24INF00083B', 'nom' => 'MATOUALA TOUMANSI PRINCE BENYJ', 'telephone' => null, 'email' => 'prince.matouala@iua.ci'],
            ['matricule' => '24INF01449S', 'nom' => 'M\'BANDAN YVES ARMEL GOUYA', 'telephone' => null, 'email' => 'armel.m\'bandan@iua.ci'],
            ['matricule' => '24INF00808S', 'nom' => 'MEANGO  PATRICK EMMANUEL GBO', 'telephone' => null, 'email' => 'emmanuel.meango@iua.ci'],
            ['matricule' => '24INF01498S', 'nom' => 'MEL ESSOH JAURES WILFRIED', 'telephone' => null, 'email' => 'jaures.mel@iua.ci'],
            ['matricule' => '24INF03051S', 'nom' => 'MEL NOEMIE AUDE-MARIE CHLOE', 'telephone' => null, 'email' => 'marie.mel@iua.ci'],
            ['matricule' => '24INF01507', 'nom' => 'N\'CHIAIN  MANFOUET WILFRIED JU', 'telephone' => null, 'email' => 'wilfried.n\'chiain@iua.ci'],
            ['matricule' => '24INF00718S', 'nom' => 'N\'DIAYE SAMIRA KENZA IMAN', 'telephone' => null, 'email' => 'kenza.n\'diaye@iua.ci'],
            ['matricule' => '24INF00126B', 'nom' => 'N\'DJA ULRICH IVAN GEOFFROY', 'telephone' => null, 'email' => 'ivan.n\'dja@iua.ci'],
            ['matricule' => '24INF00358S', 'nom' => 'N\'DOHOU TANOH EDEN TREVOR', 'telephone' => null, 'email' => 'eden.n\'dohou@iua.ci'],
            ['matricule' => '24INF00441S', 'nom' => 'N\'DOLLY BONI MAXWELL PATRICK', 'telephone' => null, 'email' => 'maxwell.n\'dolly@iua.ci'],
            ['matricule' => '24INF01579S', 'nom' => 'N\'GUESSAN  DENIN TRACY ANGE TR', 'telephone' => null, 'email' => 'ange.n\'guessan@iua.ci'],
            ['matricule' => '24INF00784S', 'nom' => 'N\'GUESSAN  N\'DA SHALOM', 'telephone' => null, 'email' => 'n\'da.n\'guessan@iua.ci'],
            ['matricule' => '24INF01069S', 'nom' => 'N\'TAH KOUASSI KOUASSI JEAN EMM', 'telephone' => null, 'email' => 'jean.n\'tah@iua.ci'],
            ['matricule' => '24INF00313S', 'nom' => 'N\'TCHOBO AHOUA AMLAN ANNE  ELI', 'telephone' => null, 'email' => 'anne.n\'tchobo@iua.ci'],
            ['matricule' => '24INF00857S', 'nom' => 'N\'ZI  KOFFI GUY HERMANN', 'telephone' => null, 'email' => 'guy.n\'zi@iua.ci'],
            ['matricule' => '24INF01115S', 'nom' => 'N\'ZORE BILE VALERIE DIDIER', 'telephone' => null, 'email' => 'valerie.n\'zore@iua.ci'],
            ['matricule' => '24INF01641S', 'nom' => 'ORSOT BOSSO SAINT VIANNEY VALE', 'telephone' => null, 'email' => 'vianney.orsot@iua.ci'],
            ['matricule' => '24INF01790S', 'nom' => 'OUATTARA  GNINWOKI MOHAMED', 'telephone' => null, 'email' => 'gninwoki.ouattara@iua.ci'],
            ['matricule' => '24INF00461S', 'nom' => 'OUATTARA  ULRICH MARVIN ELIEZE', 'telephone' => null, 'email' => 'marvin.ouattara@iua.ci'],
            ['matricule' => '23INF00544', 'nom' => 'OULOU BENNIET JOEL-ANGE DANIEL', 'telephone' => null, 'email' => 'ange.oulou@iua.ci'],
            ['matricule' => '24INF00320B', 'nom' => 'OYEWOLE ABILA FAOZIA', 'telephone' => null, 'email' => 'abila.oyewole@iua.ci'],
            ['matricule' => '24INF01849S', 'nom' => 'SANGARE MARIAME', 'telephone' => null, 'email' => 'sangare.sangare@iua.ci'],
            ['matricule' => '24INF01587S', 'nom' => 'SANOGO  ARIELLE', 'telephone' => null, 'email' => 'sanogo.sanogo@iua.ci'],
            ['matricule' => '24INF01596S', 'nom' => 'SIDIBE ROKYATOU AL FATTAH', 'telephone' => null, 'email' => 'al.sidibe@iua.ci'],
            ['matricule' => '24INF00247S', 'nom' => 'SOULAMA KORONFIEN JEAN MOREL I', 'telephone' => null, 'email' => 'morel.soulama@iua.ci'],
            ['matricule' => '24INF01522S', 'nom' => 'SOUMAHORO IBRAHIM ABDOUL MALICK', 'telephone' => null, 'email' => 'abdoul.soumahoro@iua.ci'],
            ['matricule' => '24INF00771S', 'nom' => 'SYLLA  LOSSENI AYOUBA', 'telephone' => null, 'email' => 'losseni.sylla@iua.ci'],
            ['matricule' => '24INF01588S', 'nom' => 'TIBE  GRACE SHEMIDA', 'telephone' => null, 'email' => 'grace.tibe@iua.ci'],
            ['matricule' => '24INF00907S', 'nom' => 'TIMITE  BEN-ALI DESIRE', 'telephone' => null, 'email' => 'ali.timite@iua.ci'],
            ['matricule' => '24INF00770S', 'nom' => 'TOSSOU  FRED JEAN ISAAC', 'telephone' => null, 'email' => 'jean.tossou@iua.ci'],
            ['matricule' => '24INF01776S', 'nom' => 'TRAORE  MOUSSA NOËL', 'telephone' => null, 'email' => 'moussa.traore@iua.ci'],
            ['matricule' => '24INF00640S', 'nom' => 'WADJAS MOYHE ARMEL', 'telephone' => null, 'email' => 'moyhe.wadjas@iua.ci'],
            ['matricule' => '24INF01550S', 'nom' => 'YAO  KOUAME NATHAN', 'telephone' => null, 'email' => 'kouame.yao@iua.ci'],
            ['matricule' => '24INF00603S', 'nom' => 'YAO SEBEYE AIME VIDAL', 'telephone' => null, 'email' => 'aime.yao@iua.ci'],
            ['matricule' => '24INF00532B', 'nom' => 'YAPI PETHUEL CHRIS-LEMEC KAHON', 'telephone' => null, 'email' => 'lemec.yapi@iua.ci'],
            ['matricule' => '24INF00896S', 'nom' => 'KONE KINDANA KHADIDJA', 'telephone' => null, 'email' => 'kindana.kone@iua.ci'],
            ['matricule' => '25INF04512S', 'nom' => 'BONI MARIE-PERLE', 'telephone' => null, 'email' => 'marie.boni@iua.ci'],
            ['matricule' => '24INF01772S', 'nom' => 'KABRAN MANFOI FATY CARLA-CLAIRE', 'telephone' => null, 'email' => 'carla.kabran@iua.ci'],
            ['matricule' => '24INF00489B', 'nom' => 'KISSA AKA SAMUEL', 'telephone' => null, 'email' => 'aka.kissa@iua.ci'],
            ['matricule' => '24INF01438S', 'nom' => 'KOUTE OKIA GRACE NAHOMIE', 'telephone' => null, 'email' => 'grace.koute@iua.ci'],
            ['matricule' => '24INF00266S', 'nom' => 'LOHI ULRICH JASON ELISEE', 'telephone' => null, 'email' => 'jason.lohi@iua.ci'],
            ['matricule' => '25INF05080S', 'nom' => 'ASSA JEAN DÉSIRÉ FAAYE BENOIT', 'telephone' => null, 'email' => 'faaye.assa@iua.ci'],
            ['matricule' => '25INFO5036S', 'nom' => 'KOUASSI EMMANUEL SERGE NEHEMIEA', 'telephone' => null, 'email' => 'serge.kouassi@iua.ci'],
            ['matricule' => '24INF00433S', 'nom' => 'COULIBALY  MOHAMAD PRINCE YACOU', 'telephone' => null, 'email' => 'prince.coulibaly@iua.ci'],
            ['matricule' => '24INF01398S', 'nom' => 'DIALLO AÏSSATOU', 'telephone' => null, 'email' => 'diallo.diallo@iua.ci'],
            ['matricule' => '24INF00887S', 'nom' => 'SYLLA LOSSENY AYOUBA', 'telephone' => null, 'email' => 'losseny.sylla@iua.ci'],
            ['matricule' => '24INF04002S', 'nom' => 'LASME SOVE IVAN ARMEL', 'telephone' => null, 'email' => 'ivan.lasme@iua.ci'],
            ['matricule' => '23INFO2206', 'nom' => 'MOUSSA ABDOUL MAJID', 'telephone' => null, 'email' => 'abdoul.moussa@iua.ci'],
            ['matricule' => '24INF00497B', 'nom' => 'YAO DAVID JEPHTHE OTHINIEL', 'telephone' => null, 'email' => 'jephthe.yao@iua.ci'],
            ['matricule' => '24SBT00345B', 'nom' => 'KRANA HAINA', 'telephone' => null, 'email' => 'krana.krana@iua.ci'],
            ['matricule' => '25INF04688S', 'nom' => 'DIOMANDÉ SIAMA ERICKA ALEXANDRINE', 'telephone' => null, 'email' => 'ericka.diomandé@iua.ci'],
            ['matricule' => '24INF00577S', 'nom' => 'KOULARAMBAYE DJINODJI SOSTHENE', 'telephone' => null, 'email' => 'djinodji.koularambaye@iua.ci'],
            ['matricule' => '25INF04492S', 'nom' => 'OUGA LOU DJESSAN URSULA AMOUR', 'telephone' => null, 'email' => 'ursula.ouga@iua.ci'],
            ['matricule' => '24INF03064S', 'nom' => 'DIABAGATE ALI EL HADJ', 'telephone' => null, 'email' => 'el.diabagate@iua.ci'],
            ['matricule' => '24INF00562S', 'nom' => 'YEBOUA KOUADIO MERVYNE YVANN RUFUS', 'telephone' => null, 'email' => 'yvann.yeboua@iua.ci'],
            ['matricule' => '24INF01616S', 'nom' => 'MAMBO CHRIST ARIEL', 'telephone' => null, 'email' => 'christ.mambo@iua.ci'],
            ['matricule' => '24INF01547S', 'nom' => 'NENE BI KICKO YOANN SAMUEL ROLAND', 'telephone' => null, 'email' => 'samuel.nene@iua.ci'],
            ['matricule' => '24INF03006S', 'nom' => 'TRAORE AWA SORAYA IRIANE-KENETTE', 'telephone' => null, 'email' => 'iriane.traore@iua.ci'],
            ['matricule' => '25INFO5274S', 'nom' => 'EHOUE AUDREY', 'telephone' => null, 'email' => 'ehoue.ehoue@iua.ci'],
            ['matricule' => '25INF016130B', 'nom' => 'TRAORE KHADIDIA MAHAMANE', 'telephone' => null, 'email' => 'khadidia.traore@iua.ci'],
            ['matricule' => '25INF4040S', 'nom' => 'KOUACOU TANOH CHRIST JEAN FIDEL', 'telephone' => null, 'email' => 'jean.kouacou@iua.ci'],
            ['matricule' => '22MA02116', 'nom' => 'FOFANA FAKEMO', 'telephone' => null, 'email' => 'fofana.fofana@iua.ci'],
            ['matricule' => '25INFO5424S', 'nom' => 'KONE ABDOUL HAFIZ', 'telephone' => null, 'email' => 'abdoul.kone@iua.ci'],
            ['matricule' => '24INF00339S', 'nom' => 'SANOGO CHEICK OUMAR', 'telephone' => null, 'email' => 'cheick.sanogo@iua.ci'],
            ['matricule' => '25INFO05420S', 'nom' => 'TANOH KASSI FRANCK ULRICH MICHAËL', 'telephone' => null, 'email' => 'ulrich.tanoh@iua.ci'],
            ['matricule' => '25INFO575S', 'nom' => 'ACHAPO YAPI', 'telephone' => null, 'email' => 'achapo.achapo@iua.ci'],
            ['matricule' => '24INFO2038S', 'nom' => 'KAMAGATÉ ISAAC SAMUEL', 'telephone' => null, 'email' => 'isaac.kamagaté@iua.ci'],
            ['matricule' => '24INF00467B', 'nom' => 'BITTY MIREILLE', 'telephone' => null, 'email' => 'bitty.bitty@iua.ci'],
            ['matricule' => '24INF00462B', 'nom' => 'DOSSO YAN AZIZ', 'telephone' => null, 'email' => 'yan.dosso@iua.ci'],
        ];

        $count = 0;

        foreach ($etudiants as $ligne) {
            try {
                $etudiant = new L2GI();
                $etudiant->id = (string) Str::uuid();
                $etudiant->matricule = $ligne['matricule'];
                $etudiant->nom = $ligne['nom'];
                $etudiant->telephone = $ligne['telephone'];
                $etudiant->email = $ligne['email'];
                $etudiant->save();
                $count++;
            } catch (\Illuminate\Database\QueryException $e) {
                $this->command->warn("     - Doublon ignoré (matricule/téléphone/email déjà utilisé) : {$ligne['matricule']} - {$ligne['nom']}");
            }
        }

        $this->command->info("     - {$count} étudiants L2 GI créés");
    }
}